### PR TITLE
Eliminate Undefined Attributes

### PR DESCRIPTION
**Pull request by volfkarlo**
Changelog:
- added check for attribute value type - if true bailout

Bug example:
columns example
wrapper bg color example

### CODE REVIEW

**Review by goranalkovic-infinum — APPROVED** [review]

**Review by dingo-d — APPROVED** [review]

**Comment by volfkarlo** [comment]
Two tests failed.
The first one is an easy fix. 
get colors

The second one is trying to extract a function that doesn't exist.
build window object

@iruzevic this might be the function for running scripts in editor (import blogposts, injecting the blocks...). Could you please take a look?

**Comment by IvanGrginovInf** [comment]
@volfkarlo tests are failing because https://github.com/infinum/eightshift-frontend-libs/pull/390 wasn't merged in develop. Once that is merge, just pull the latest develop into your branch and it should work fine.

**Comment by dingo-d** [comment]
> Once that is merge, just pull the latest develop into your branch and it should work fine.

Or rebase 😄

**Comment by volfkarlo** [comment]
I ran all the tests locally and it seems fine. I'll just wait for the confirmation on Github tests.

**Pull request merged**
